#!/usr/bin/env python3
"""Tests for tools/ingest_dkc3_disasm.py on a synthetic H4v0c21-style tree."""
import os
import sys
import tempfile
import unittest
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY / "tools"))
sys.path.insert(0, str(REPOSITORY / "snesrecomp" / "tools"))

import ingest_dkc3_disasm as ingest  # noqa: E402

BANK_80 = """\
CODE_808000:
\tJSR sprite_main\t\t\t;$808000
\tJSL CODE_B28000\t\t\t;$808003
\tRTS\t\t\t\t;$808007

sprite_main:
\tJMP (.state_table,x)\t\t;$808008

.state_table:
\tdw .state_0
\tdw .state_1

.state_0:
\tLDA #$0001\t\t\t;$80800F
\tRTS\t\t\t\t;$808012

.state_1:
\tJSR (DATA_808020,x)\t\t;$808013
\tRTS\t\t\t\t;$808016

DATA_808017:
\tdb $01,$02,$03,$04,$05,$06,$07,$08,$09

DATA_808020:
\tdw CODE_808024
\tdw CODE_808026

CODE_808024:
\tRTS\t\t\t\t;$808024

CODE_808026:
\tJMP ($0042)\t\t\t;$808026
"""

BANK_B2 = """\
CODE_B28000:
\tRTL\t\t\t\t;$B28000
"""

SYMBOLS = """\
;no$sns symbolic information file
;generated by asar

00808000 CODE_808000
00808008 sprite_main
0080800B sprite_main_state_table
0080800F sprite_main_state_0
00808013 sprite_main_state_1
00808017 DATA_808017
00808020 DATA_808020
00808024 CODE_808024
00808026 CODE_808026
00B28000 CODE_B28000
"""


class IngestTest(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        root = Path(self.temp.name)
        (root / "bank_80.asm").write_text(BANK_80)
        (root / "bank_B2.asm").write_text(BANK_B2)
        (root / "dkc3.sym").write_text(SYMBOLS)
        self.root = root

    def tearDown(self):
        self.temp.cleanup()

    def test_symbols_and_direct_targets(self):
        symbols = ingest.load_nocash_symbols(self.root / "dkc3.sym")
        self.assertEqual(len(symbols), 10)
        by_name = {name: pc for pc, name in symbols}
        targets, unresolved = ingest.collect_direct_targets(self.root, by_name)
        self.assertEqual(targets, {"sprite_main", "CODE_B28000"})
        self.assertEqual(sum(unresolved.values()), 0)

    def test_table_dispatches(self):
        symbols = ingest.load_nocash_symbols(self.root / "dkc3.sym")
        by_name = {name: pc for pc, name in symbols}
        contracts, skipped = ingest.collect_table_dispatches(self.root, by_name)
        by_site = {(c.bank, c.site_pc16): c for c in contracts}
        # The dot-local state table resolves through its parent.
        jump = by_site[(0x80, 0x8008)]
        self.assertEqual(jump.mode, "ptrtail")
        self.assertEqual(jump.targets, (0x80800F, 0x808013))
        # A global table reached by JSR is a call dispatch.
        call = by_site[(0x80, 0x8013)]
        self.assertEqual(call.mode, "ptrcall")
        self.assertEqual(call.targets, (0x808024, 0x808026))
        # A RAM pointer has no symbolic table and is left to the interpreter.
        self.assertNotIn((0x80, 0x8026), by_site)
        self.assertEqual(dict(skipped), {})

    def test_label_data_regions(self):
        symbols = ingest.load_nocash_symbols(self.root / "dkc3.sym")
        regions = ingest.collect_label_data_regions(self.root, symbols)
        # The state table, the byte block, and the pointer table are data;
        # the byte block and pointer table are adjacent and merge.
        self.assertEqual(regions, [(0x80, 0x800B, 0x800F), (0x80, 0x8017, 0x8024)])

    def test_end_to_end_cfg(self):
        out = Path(self.temp.name) / "cfg"
        argv = sys.argv
        sys.argv = ["ingest", "--disasm", str(self.root), "--output", str(out)]
        try:
            self.assertEqual(ingest.main(), 0)
        finally:
            sys.argv = argv
        text = (out / "bank80.cfg").read_text()
        self.assertIn("bank = 0x80", text)
        self.assertIn("indirect_dispatch 8008 2 ptrtail targets:80800F,808013", text)
        self.assertIn("indirect_dispatch 8013 2 ptrcall targets:808024,808026", text)
        self.assertIn("data_region 80 8017 8024", text)
        self.assertIn("func sprite_main 8008", text)
        self.assertIn("tools/ingest_dkc3_disasm.py", text)
        self.assertTrue((out / "bankb2.cfg").exists())
        self.assertTrue((out / ".ingest" / "dkc3_full.sym").exists())


if __name__ == "__main__":
    unittest.main()
